### ISSUE TITLE
push notifications ?

### ISSUE THREAD

**Issue by michabbb** [InterNetX/autodns-rabbitmq-php-proxy#1]
hi @mschrieck ,

wie und wo kann man diese aktivieren ? gibts da eine doku zu ? ;)

merci

**Comment by mortensen** [comment]
Hallo @michabbb .

Sorry für die etwas verspätete Antwort. Es gibt im Help-Center einen Artikel zum Thema "Push-Benachrichtigungen". 

https://de.help.internetx.com/display/APIPROCESSDE/Asynchrone+Benachrichtigungen#AsynchroneBenachrichtigungen-Push

Hilft dir das weiter?

Gruß
Frederik

**Comment by michabbb** [comment]
wenn die seite das beispielscript laden würde (unten auf der seite) 😏 ich sehe leider nur den lade-kreisel ....

**Comment by mortensen** [comment]
@michabbb  Hmn ok das kläre ich. Danke für den Hinweis. Kann aber unter Umständen bis Montag dauern, bis ich hier Informationen habe.

**Comment by michabbb** [comment]
nagut, was man nicht sieht, kann ja trotzdem da sein 😏 
ich schau mal, was ich damit anfangen kann, danke !

![image](https://user-images.githubusercontent.com/3524595/68476523-27096d80-022b-11ea-9e65-d4160e089ce7.png)

**Comment by mortensen** [comment]
@michabbb  Die Mehrsprachigkeit des Help-Centers wird derzeit überarbeitet, weswegen es zu Problemen mit dem von mir genannten Link kam.

Unter folgendem Link solltest du aber den Quellcode angezeigt bekommen:
https://help.internetx.com/display/APIPROCESSDE/Asynchrone+Benachrichtigungen

Gruß
Frederik

**Comment by michabbb** [comment]
@mortensen danke für die Info 👍
